apiVersion: v1
kind: Secret
metadata:
  name: myprivatedockerregistry-pull-secret
data:
  .dockerconfigjson: e2F1dGhzOntodHRwczovL2luZGV4LmRvY2tlci5pby92MS86e3VzZXJuYW1lOmRvY2tlcnVzZXJuYW1lLHBhc3N3b3JkOnlvdXJwYXNzd29yZCxlbWFpbDp5b3VyZW1haWxAZ21haWwuY29tLGF1dGg6eW91cmVuY3J5cHRlZHBhc3N3b3JkfX19Cg==
type: kubernetes.io/dockerconfigjson